### ISSUE TITLE
Beakn - Serial Connection question....

### ISSUE THREAD

**Issue by grantckohler** [jonbgallant/beakn#1]
Within the source code, I'm trying to identify where i would start modify the serial connection to pro-actively "probe" or wait for the specific com port, in an attempt to reconnect without force closing and re-opening the app. If anything, wait for that device to become available again before reestablishing the serial connection and parsing the last status. 

Something like this:
If Beakn loses serial connection, wait for com port
Com port becomes available, reconnect, relay current status

Or maybe tie the app to wait for the unique hardware identifier of the serial device? 

I use this in my laptop dock at work and as a work-around and have a batch to kill and relaunch. I'm relatively more of a hardware guy, so this would be something i work with my programmer bud on.

I'm just curious where i would need to start since this is probably the first application source I've jumped into. I appreciate your time spent on this project! Let me know if i can send some coffee or a gift your way.

**Comment by jongio** [comment]
Sorry for the multi-year delay - starting to work on this project again.  I would start here: https://github.com/jonbgallant/beakn/blob/master/desktop/beakn/beakn/Protocol/Serial.cs

CmdMessenger Library might already have something like that in it.  If you git clone https://github.com/jonbgallant/beakn.git --recursive" you will see the Arduino-CmdMessenger project in the beakn root and the original project is here: https://github.com/thijse/Arduino-CmdMessenger

**Comment by jongio** [comment]
Closing. LMK if you still need help.
