### ISSUE TITLE
Cannot use named IP adress for MQTT

### ISSUE THREAD

**Issue by tvillingett** [jonbgallant/beakn#3]
I can only use the corresponding IP number and not a named IP address when configuring broker for MQTT:
Instead of
`<add key="MqttHost" value="test.mosquitto.org" />`
I had to use:
`<add key="MqttHost" value="37.187.106.16" />`

**Comment by jongio** [comment]
Sorry for the super long delay on this.  I updated to latest mqtt libs and it seems to have fixed the issue.  Can you try it out when you get a chance?

https://github.com/jonbgallant/beakn/releases/tag/v0.4.4-beta

**Comment by tvillingett** [comment]
It works now, but it works with 0.4.3 as well.
