### ISSUE TITLE
Doesn't work with latest SFB build

### ISSUE THREAD

**Issue by ghost** [jonbgallant/beakn#4]
This is the version:-
![image](https://cloud.githubusercontent.com/assets/21270291/19939537/b3500b36-a0e6-11e6-8fcc-3024e705ae7b.png)

And this is the error:-

![image](https://cloud.githubusercontent.com/assets/21270291/19939518/9f3a30d6-a0e6-11e6-8df9-7a0bd5c65726.png)

**Comment by jongio** [comment]
Can you please try with this version? https://github.com/jonbgallant/beakn/releases/tag/v0.4.3

I made a few updates and it is working on my machine now.
